### ISSUE TITLE
compress error

### ISSUE THREAD

**Issue by JasonHuangHuster** [hn/woff-compress#1]
WOFF TableDirectoryEntry 7 broken (length  mismatches 294832) at D:\woff-compres
s.pl line 139.

**Comment by hn** [comment]
Maybe your .woff file is broken. Try to start woff-compress with "-vv" verbose debug info. This will show you a list of TableDirectoryEntries and their length compressed and uncompressed.

**Comment by JasonHuangHuster** [comment]
D:>woff-compress.pl   fontawesome-webfont.woff out.woff -vv
WOFF TableDirectoryEntry 5 broken (length  mismatches 126180) at D:\woff-compres
s.pl line 139.

i'm running this on windows , do i have to install Zopfli ?

**Comment by hn** [comment]
You have to place the `-vv` directly after the command name (`woff-compress.pl -vv`).

I don't know if this program works on windows at all. At least you would have to adjust the line `my $zopfli="/usr/bin/zopfli";` to match the zopfli executable path. Sorry, I can't help you with that.

**Comment by hn** [comment]
No more info received, closing issue

**Comment by mgreter** [comment]
This is probably fixed by PR #2. @JasonHuangHuster indicated he's using windows, so his font probably got mixed up by some return character conversion. I encountered the same issue which was fixed by #2.
