### ISSUE TITLE
Didn't compress

### ISSUE THREAD

**Issue by zubair-temi** [hn/woff-compress#4]
Tried to compress my woff file with `./woff-compress.pl -v in.woff out.woff` and it barely reduced size. Is there any way I can use it to reduce substantially.

Output
```
Original file size: 8937608, compressed size: 8884648 (0.59% reduction)
```

**Comment by hn** [comment]
With lossless compression, there ist no way to do it -- as far as I know.

You might try [lossy compression](https://stackoverflow.com/questions/2635423/way-to-reduce-size-of-ttf-fonts)
